name: Project CI

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - tests/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run project pipeline
        run: |
          chmod +x project/pipeline.sh
          ./project/pipeline.sh

      - name: Run tests
        run: |
          pytest
